apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-dashy-conf"
data:
  conf: |
    # Page meta info, like heading, footer text and nav links
    pageInfo:
      title: Chester's Homelab
      description: Please just work you stupid machine
      navLinks:
      - title: Dashy Documentation
        path: https://dashy.to/docs
    
    # Optional app settings and configuration
    appConfig:
      theme: colorful
      
    # Main content - An array of sections, each containing an array of items
    sections:
    - name: Pipeline
      icon: fas fa-rocket
      items:
      - title: Argo CD
        description: Argo CD dashboard for cluster
        #icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: https://argocd.{{ .Values.private_top_level_domain }}/
        target: newtab
      - title: Argo Workflows
        description: Argo Workflows dashboard for cluster
        #icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: http://argowf.{{ .Values.private_top_level_domain }}/
        target: newtab
      - title: traefik
        description: traefik dashboard
        #icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: https://traefik.{{ .Values.private_top_level_domain }}/
        target: newtab
      # - title: GitHub
      #   description: Source Code, Issues and Pull Requests
      #   url: https://github.com/lissy93/dashy
      #   icon: favicon
      # - title: Docs
      #   description: Configuring \u0026 Usage Documentation
      #   provider: Dashy.to
      #   icon: far fa-book
      #   url: https://dashy.to/docs
      # - title: Showcase
      #   description: See how others are using Dashy
      #   url: https://github.com/Lissy93/dashy/blob/master/docs/showcase.md
      #   icon: far fa-grin-hearts
      # - title: Config Guide
      #   description: See full list of configuration options
      #   url: https://github.com/Lissy93/dashy/blob/master/docs/configuring.md
      #   icon: fas fa-wrench
      # - title: Support
      #   description: Get help with Dashy, raise a bug, or get in contact
      #   url: https://github.com/Lissy93/dashy/blob/master/.github/SUPPORT.md
      #   icon: far fa-hands-helping"
    - name: Production
      icon: fas fa-rocket
      items:
      - title: PG Admin
        description: PG admin dashboard
        #icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: http://pgadmin-production.{{ .Values.private_top_level_domain }}/
        target: newtab
      - title: aspire dashboard
        description: aspire dashboard
        #icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: http://aspire-dashboard-production.{{ .Values.private_top_level_domain }}/
        target: newtab
      - title: ping api private
        description: ping api
        #icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: http://ping-production.{{ .Values.private_top_level_domain }}/health
        target: newtab
      - title: ping api public
        description: ping api
        #icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: https://ping-production-{{ .Values.cluster_name }}.{{ .Values.public_top_level_domain }}/health
        target: newtab
    - name: Staging
      icon: fas fa-rocket
      items:
      - title: PG Admin
        description: PG admin dashboard
        #icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: http://pgadmin-staging.{{ .Values.private_top_level_domain }}/
        target: newtab
      - title: aspire dashboard
        description: aspire dashboard
        #icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: http://aspire-dashboard-staging.{{ .Values.private_top_level_domain }}/
        target: newtab
      - title: ping api private
        description: ping api
        #icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: http://ping-staging.{{ .Values.private_top_level_domain }}/health
        target: newtab
      - title: ping api public
        description: ping api
        #icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: https://ping-staging-{{ .Values.cluster_name }}.{{ .Values.public_top_level_domain }}/health
        target: newtab

