apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "hl-pipeline"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: pipeline/chart
    repoURL: https://github.com/chestercodes/hl2.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.{{ .Values.cluster_name }}.yaml
  destination:
    namespace: pipeline
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

