apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hl-ping-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://github.com/chestercodes/hl2-ping.git
    targetRevision: HEAD
    path: infra/chart
    helm:
      valueFiles:
      - values.{{ .Values.cluster_name }}.yaml
      - versions/production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
