apiVersion: v1
kind: Service
metadata:
  name: maindb
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
    - name: tcp-postgresql
      nodePort: null
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/name: postgresql
  sessionAffinity: None
  type: ClusterIP


