apiVersion: v1
kind: Secret
metadata:
  name: maindb-postgresql
  namespace: "staging"
  annotations:
    # sync number means that hopefully this will be created before the apps
    argocd.argoproj.io/sync-wave: "-5"
stringData:
  postgres-password: password1
  migrations-password: password2
