apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hl-cluster-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://github.com/chestercodes/hl2.git
    targetRevision: HEAD
    path: cluster/chart
    helm:
      valueFiles:
      - values.homelab.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
